FROM openeuler/openeuler:22.03-lts-sp1
ENV PATH="$PATH:/home/eulercopilot/.local/bin"

RUN sed -i 's|http://repo.openeuler.org/|https://mirrors.huaweicloud.com/openeuler/|g' /etc/yum.repos.d/openEuler.repo &&\
    yum makecache && \
    yum update -y &&\
    yum install -y python3 python3-pip shadow-utils && \
    yum clean all && \
    groupadd -g 1001 eulercopilot && useradd -u 1001 -g 1001 eulercopilot

USER eulercopilot
COPY --chown=1001:1001 requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt -i https://repo.huaweicloud.com/repository/pypi/simple && \
    chmod -R 750 /home/eulercopilot
